config {
    type: "table", 
    schema: "zx_demo", 
    tags: ["demo"]
}

with makt as (
    select * except (maktx) , 
    case when maktx  = 'Zero Fat Ice cream' then 'Zero Fat Ice Cream' 
         else trim(maktx) 
    end maktx 
    from 
    ${ref({schema:"CORTEX_SAP_RAW",name:"makt"})}
QUALIFY ROW_NUMBER() OVER(PARTITION BY mandt,matnr ORDER BY recordstamp DESC) = 1
), mara as (
  select *
  from 
  ${ref({schema:"CORTEX_SAP_RAW",name:"mara"})}
  QUALIFY ROW_NUMBER() OVER(PARTITION BY mandt,matnr ORDER BY recordstamp DESC) = 1
)
select 
distinct 
a.mandt client,
a.matnr material_number, 
b.maktx material_description,
a.ersda created_on, 
a.ernam created_by, 
a.laeda last_changed, 
a.aenam changed_by, 
a.mtart material_type, 
a.matkl material_group, 
a.bstme order_unit, 
a.brgew gross_weight, 
a.ntgew net_weight
from mara a 
inner join makt b 
on a.matnr = b.matnr

