config {
    type: "table", 
    schema: "zx_demo", 
    tags: ["demo"]
}

with header as (
SELECT  
*
FROM ${ref({schema:"CORTEX_SAP_RAW",name:"vbak"})}
QUALIFY ROW_NUMBER() OVER(PARTITION BY mandt,vbeln  ORDER BY recordstamp DESC) = 1
), item as (
  SELECT  
 distinct *
FROM ${ref({schema:"CORTEX_SAP_RAW",name:"vbap"})}
QUALIFY ROW_NUMBER() OVER(PARTITION BY mandt,vbeln,posnr  ORDER BY recordstamp DESC) = 1
)
select 
distinct 
a.mandt client , 
a.vbeln sales_doc_header_number, 
a.erdat created_on, 
a.erzet created_time, 
a.ernam created_by, 
a.netwr net_value, 
a.auart sale_doc_type, 
a.audat last_changed, 
a.vkorg sales_org, 
a.vtweg distribution_channel, 
a.spart division, 
a.kunnr sold_to_party, 
b.posnr sales_doc_item, 
b.matnr material_number, 
b.arktx short_text_item, 
b.kwmeng order_qty, 
b.vrkme sales_unit, 
b.netwr item_net_value, 
b.werks plant, 
b.lgort storage_location, 
b.route shipping_route, 
b.abgru reason_rejection
from header a 
inner join item b 
on a.vbeln = b.vbeln
and a.mandt = b.mandt 
